"""journal privacy/anonimousity added

Revision ID: b55423461bc7
Revises: 49a0150da602
Create Date: 2022-08-20 12:17:10.330062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b55423461bc7'
down_revision = '49a0150da602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.add_column('journals', sa.Column('is_anonymous', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journals', 'is_anonymous')
    op.drop_column('journals', 'is_private')
    # ### end Alembic commands ###
